#!/bin/bash

# Copyright IBM Corp, 2015
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

# This script is based on code from the Kandan project:
# https://github.com/kandanapp/kandan/blob/master/gen-changelog.sh

echo "CHANGELOG"
echo "========="
echo
git for-each-ref --sort='*authordate' --format='%(tag)' refs/tags | tac |grep -v '^$' | while read TAG ; do
    if [ $NEXT ]; then
        echo "#### [$NEXT] ####"
    elif [ "$1" != "--release" ]; then
        echo "#### [Current] ####"
    else
        NEXT=$TAG
        continue
    fi
    GIT_PAGER=cat git log --pretty=format:" * [%h] %<(78,trunc)%s (%an)" $TAG..$NEXT
    NEXT=$TAG
    echo; echo
done
FIRST=$(git for-each-ref --sort='*authordate' --format='%(tag)' refs/tags | head -1)

echo "#### [$FIRST] ####"
GIT_PAGER=cat git log --pretty=format:" * [%h] %<(78,trunc)%s (%an)" $FIRST
