#!/bin/sh
#
# Copyright 2008-2012 Red Hat, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301 USA

# tags and output versions:
#   - kimchi-ginger-1.2.0   => 1.2.0 (upstream clean)
#   - kimchi-ginger-1.2.0-1 => 1.2.0 (downstream clean)
#   - kimchi-ginger-1.2.0-2-g34e62f   => 1.2.0 (upstream dirty)
#   - kimchi-ginger-1.2.0-1-2-g34e62f => 1.2.0 (downstream dirty)
AWK_VERSION='
    BEGIN { FS="-" }
    /^kimchi-ginger-[0-9]/ {
      sub(/^kimchi-ginger-/,"") ; print $1
    }'

# tags and output releases:
#   - kimchi-ginger-1.2.0   => 0 (upstream clean)
#   - kimchi-ginger-1.2.0-1 => 1 (downstream clean)
#   - kimchi-ginger-1.2.0-2-g34e62f1   => 2.git34e62f1 (upstream dirty)
#   - kimchi-ginger-1.2.0-1-2-g34e62f1 => 1.2.git34e62f1 (downstream dirty)
AWK_RELEASE='
    BEGIN { FS="-"; OFS="." }
    /^kimchi-ginger-[0-9]/ {
      sub(/^kimchi-ginger-/,"")
      if (NF == 1) print 0
      else if (NF == 2) print $2
      else if (NF == 3) print $2, "git" substr($3, 2)
      else if (NF == 4) print $2, $3, "git" substr($4, 2)
    }'

PKG_VERSION=`git describe --tags --match "kimchi-ginger-[0-9]*" 2> /dev/null || cat VERSION 2> /dev/null`

if test "x$1" = "x--full"; then
    echo $PKG_VERSION | tr -d '[:space:]'
elif test "x$1" = "x--version"; then
    echo $PKG_VERSION | awk "$AWK_VERSION" | tr -cd '[:alnum:].'
elif test "x$1" = "x--release"; then
    echo $PKG_VERSION | awk "$AWK_RELEASE" | tr -cd '[:alnum:].'
else
    echo "usage: $0 [--full|--version|--release]"
    exit 1
fi
